# Generated by Django 4.2.10 on 2025-06-23 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_favourite_base_experience_alter_favourite_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favourite',
            name='poke_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'poke_id')},
        ),
    ]
